# Generated by Django 5.1.2 on 2025-11-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aichat",
            table="hertz_ai_AIChat",
        ),
        migrations.AlterModelTable(
            name="aichatmessage",
            table="hertz_ai_AIChatMessage",
        ),
    ]
