# Generated by Django 5.1.2 on 2025-11-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_ai", "0002_alter_aichat_table_alter_aichatmessage_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aichat",
            table="hertz_ai_ai_chat",
        ),
        migrations.AlterModelTable(
            name="aichatmessage",
            table="hertz_ai_ai_chat_message",
        ),
    ]
