# Generated by Django 5.2.6 on 2025-10-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wiki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分类描述"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="studio_django_wiki.wiki",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识分类",
                "verbose_name_plural": "知识分类",
                "db_table": "hertz_wiki",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WikiArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文章标题")),
                ("content", models.TextField(verbose_name="文章内容")),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="文章摘要"
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文章图片"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="文章状态",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="文章标签"
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="阅读量")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="studio_django_wiki.wiki",
                        verbose_name="知识分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识文章",
                "verbose_name_plural": "知识文章",
                "db_table": "hertz_wiki_article",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
