# Generated by Django 5.1.2 on 2025-11-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="wiki",
            table="hertz_wiki_wiki_category",
        ),
        migrations.AlterModelTable(
            name="wikiarticle",
            table="hertz_wiki_wiki_article",
        ),
    ]
