# Generated by Django 5.1.2 on 2026-05-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studio_django_yolo", "0014_alter_alert_table_alter_dataset_table_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarineSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="中文名称", max_length=100, verbose_name="物种名称"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        help_text="拉丁文学名", max_length=200, verbose_name="学名"
                    ),
                ),
                (
                    "common_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON 格式的俗名列表",
                        verbose_name="俗名列表",
                    ),
                ),
                (
                    "taxonomic_rank",
                    models.CharField(
                        choices=[
                            ("kingdom", "界"),
                            ("phylum", "门"),
                            ("class", "纲"),
                            ("order", "目"),
                            ("family", "科"),
                            ("genus", "属"),
                            ("species", "种"),
                        ],
                        default="species",
                        max_length=20,
                        verbose_name="分类等级",
                    ),
                ),
                (
                    "kingdom",
                    models.CharField(blank=True, max_length=100, verbose_name="界"),
                ),
                (
                    "phylum",
                    models.CharField(blank=True, max_length=100, verbose_name="门"),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, db_column="class", max_length=100, verbose_name="纲"
                    ),
                ),
                (
                    "order_name",
                    models.CharField(
                        blank=True, db_column="order", max_length=100, verbose_name="目"
                    ),
                ),
                (
                    "family",
                    models.CharField(blank=True, max_length=100, verbose_name="科"),
                ),
                (
                    "genus",
                    models.CharField(blank=True, max_length=100, verbose_name="属"),
                ),
                ("description", models.TextField(blank=True, verbose_name="形态描述")),
                (
                    "max_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最大体长 (cm)"
                    ),
                ),
                (
                    "max_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最大体重 (kg)"
                    ),
                ),
                (
                    "lifespan",
                    models.CharField(blank=True, max_length=100, verbose_name="寿命"),
                ),
                ("habitat", models.TextField(blank=True, verbose_name="栖息环境")),
                (
                    "diet",
                    models.CharField(
                        blank=True,
                        help_text="如：肉食性、草食性、杂食性",
                        max_length=50,
                        verbose_name="食性",
                    ),
                ),
                ("behavior", models.TextField(blank=True, verbose_name="行为习性")),
                ("distribution", models.TextField(blank=True, verbose_name="地理分布")),
                (
                    "depth_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="深度范围"
                    ),
                ),
                (
                    "temperature_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="温度范围"
                    ),
                ),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("LC", "无危"),
                            ("NT", "近危"),
                            ("VU", "易危"),
                            ("EN", "濒危"),
                            ("CR", "极危"),
                            ("EW", "野外灭绝"),
                            ("EX", "灭绝"),
                            ("DD", "数据缺乏"),
                            ("NE", "未评估"),
                        ],
                        default="NE",
                        max_length=10,
                        verbose_name="保护等级",
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(default=False, verbose_name="是否受保护"),
                ),
                (
                    "protection_notes",
                    models.TextField(blank=True, verbose_name="保护说明"),
                ),
                (
                    "yolo_category_id",
                    models.IntegerField(
                        blank=True,
                        help_text="对应的 YOLO 模型类别索引",
                        null=True,
                        verbose_name="YOLO 类别 ID",
                    ),
                ),
                (
                    "yolo_category_name",
                    models.CharField(
                        blank=True,
                        help_text="YOLO 模型中的类别名称",
                        max_length=100,
                        verbose_name="YOLO 类别名称",
                    ),
                ),
                (
                    "detection_count",
                    models.IntegerField(
                        default=0,
                        help_text="该物种被 YOLO 模型识别的总次数",
                        verbose_name="被识别次数",
                    ),
                ),
                (
                    "last_detected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后识别时间"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="数据来源"
                    ),
                ),
                (
                    "references",
                    models.JSONField(blank=True, default=list, verbose_name="参考文献"),
                ),
                (
                    "properties",
                    models.JSONField(blank=True, default=dict, verbose_name="额外属性"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "海洋生物物种",
                "verbose_name_plural": "海洋生物物种",
                "db_table": "hertz_marine_species",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="hertz_marin_name_307b63_idx"),
                    models.Index(
                        fields=["scientific_name"],
                        name="hertz_marin_scienti_cab7d2_idx",
                    ),
                    models.Index(
                        fields=["yolo_category_id"],
                        name="hertz_marin_yolo_ca_50c561_idx",
                    ),
                    models.Index(
                        fields=["detection_count"],
                        name="hertz_marin_detecti_fd8ed8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SpeciesDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="如：南海、东海、黄海等",
                        max_length=100,
                        verbose_name="区域名称",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON 格式：{north, south, east, west}",
                        verbose_name="坐标范围",
                    ),
                ),
                (
                    "abundance",
                    models.CharField(
                        blank=True,
                        help_text="如：常见、稀少、偶见",
                        max_length=50,
                        verbose_name="丰富度",
                    ),
                ),
                (
                    "seasonality",
                    models.CharField(
                        blank=True,
                        help_text="如：全年、夏季、冬季",
                        max_length=100,
                        verbose_name="季节性",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="studio_django_marine_species.marinespecies",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "物种分布",
                "verbose_name_plural": "物种分布",
                "db_table": "hertz_marine_species_distribution",
                "ordering": ["species", "region"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="marine_species/images/", verbose_name="图片"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="图片说明"
                    ),
                ),
                (
                    "is_reference",
                    models.BooleanField(
                        default=True,
                        help_text="参考图会显示在物种详情页",
                        verbose_name="是否参考图",
                    ),
                ),
                (
                    "photographer",
                    models.CharField(blank=True, max_length=100, verbose_name="摄影师"),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="版权许可"
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="来源链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="studio_django_marine_species.marinespecies",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "物种图片",
                "verbose_name_plural": "物种图片",
                "db_table": "hertz_marine_species_image",
                "ordering": ["species", "-is_reference", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionSpeciesMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="YOLO 检测的置信度", verbose_name="匹配置信度"
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="匹配时间"),
                ),
                (
                    "detection_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_matches",
                        to="studio_django_yolo.detectionrecord",
                        verbose_name="检测记录",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="species_matches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="检测用户",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_matches",
                        to="studio_django_marine_species.marinespecies",
                        verbose_name="匹配物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测物种匹配记录",
                "verbose_name_plural": "检测物种匹配记录",
                "db_table": "hertz_marine_detection_match",
                "ordering": ["-matched_at"],
                "indexes": [
                    models.Index(
                        fields=["detection_record"],
                        name="hertz_marin_detecti_f9b545_idx",
                    ),
                    models.Index(
                        fields=["species"], name="hertz_marin_species_eba134_idx"
                    ),
                    models.Index(
                        fields=["user"], name="hertz_marin_user_id_409504_idx"
                    ),
                ],
            },
        ),
    ]
