# Generated by Django 5.2.6 on 2025-10-22 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoloModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "version",
                    models.CharField(default="1.0", max_length=50, verbose_name="版本"),
                ),
                (
                    "model_file",
                    models.FileField(upload_to="yolo/models/", verbose_name="模型文件"),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=dict,
                        help_text="JSON格式的类别信息",
                        verbose_name="类别信息",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="是否启用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "YOLO模型",
                "verbose_name_plural": "YOLO模型",
                "db_table": "yolo_model",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to="detection/original/", verbose_name="原始文件"
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        upload_to="detection/result/", verbose_name="检测结果文件"
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[("image", "图片检测"), ("video", "视频检测")],
                        max_length=10,
                        verbose_name="检测类型",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="使用的模型名称"),
                ),
                (
                    "object_count",
                    models.IntegerField(default=0, verbose_name="检测到的对象数量"),
                ),
                (
                    "detected_categories",
                    models.JSONField(default=list, verbose_name="检测到的类别列表"),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(default=0.5, verbose_name="置信度阈值"),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="处理时间(秒)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio_django_yolo.yolomodel",
                        verbose_name="使用的模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测记录",
                "verbose_name_plural": "检测记录",
                "db_table": "detection_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
