# Generated by Django 5.2.6 on 2025-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yolomodel",
            name="model_folder_path",
            field=models.CharField(
                blank=True,
                help_text="解压后的模型文件夹路径",
                max_length=500,
                null=True,
                verbose_name="模型文件夹路径",
            ),
        ),
        migrations.AlterField(
            model_name="yolomodel",
            name="model_file",
            field=models.FileField(
                blank=True, null=True, upload_to="yolo/models/", verbose_name="模型文件"
            ),
        ),
    ]
