# Generated by Django 5.2.6 on 2025-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0002_yolomodel_model_folder_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="yolomodel",
            name="best_model_path",
            field=models.CharField(
                blank=True,
                help_text="best.pt文件的完整路径",
                max_length=500,
                null=True,
                verbose_name="最佳模型路径",
            ),
        ),
        migrations.AddField(
            model_name="yolomodel",
            name="last_model_path",
            field=models.CharField(
                blank=True,
                help_text="last.pt文件的完整路径",
                max_length=500,
                null=True,
                verbose_name="最后模型路径",
            ),
        ),
    ]
