# Generated by Django 5.2.6 on 2025-10-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studio_django_yolo",
            "0003_yolomodel_best_model_path_yolomodel_last_model_path",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrecord",
            name="avg_confidence",
            field=models.FloatField(
                blank=True,
                help_text="所有检测对象的平均置信度",
                null=True,
                verbose_name="平均置信度",
            ),
        ),
        migrations.AddField(
            model_name="detectionrecord",
            name="confidence_scores",
            field=models.JSONField(
                default=list,
                help_text="检测到的每个对象的置信度分数",
                verbose_name="真实置信度列表",
            ),
        ),
    ]
