# Generated by Django 5.2.6 on 2025-10-23 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0004_detectionrecord_avg_confidence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detection_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="检测用户",
            ),
        ),
        migrations.AddField(
            model_name="detectionrecord",
            name="user_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="用户名称"
            ),
        ),
    ]
