# Generated by Django 5.2.6 on 2025-10-23 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studio_django_yolo",
            "0005_detectionrecord_user_detectionrecord_user_name",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名称"
                    ),
                ),
                (
                    "alert_level",
                    models.IntegerField(
                        default=0, help_text="数字越小等级越高", verbose_name="告警等级"
                    ),
                ),
                (
                    "alert_category",
                    models.CharField(
                        help_text="检测到的对象类别",
                        max_length=100,
                        verbose_name="告警类别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("deleted", "已删除")],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "detection_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert",
                        to="studio_django_yolo.detectionrecord",
                        verbose_name="关联的检测记录",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警记录",
                "verbose_name_plural": "告警记录",
                "db_table": "alert",
                "ordering": ["alert_level", "-created_at"],
            },
        ),
    ]
