# Generated by Django 5.2.6 on 2025-10-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0006_alert"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="类别名称")),
                (
                    "category_id",
                    models.IntegerField(
                        default=0, help_text="模型中的类别索引", verbose_name="类别ID"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="类别描述")),
                (
                    "alert_level",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        default="medium",
                        max_length=10,
                        verbose_name="告警等级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_categories",
                        to="studio_django_yolo.yolomodel",
                        verbose_name="关联模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型类别",
                "verbose_name_plural": "模型类别",
                "db_table": "model_category",
                "ordering": ["model", "category_id"],
                "unique_together": {("model", "category_id")},
            },
        ),
    ]
