# Generated by Django 5.2.6 on 2025-10-24 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0007_modelcategory_alert_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcategory",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="用于显示的别名，如果为空则使用类别名称",
                max_length=100,
                verbose_name="类别别名",
            ),
        ),
    ]
