# Generated by Django 5.2.6 on 2025-10-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0008_add_alias_to_model_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_level",
            field=models.CharField(
                choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                default="medium",
                max_length=10,
                verbose_name="告警等级",
            ),
        ),
    ]
