# Generated by Django 5.2.6 on 2025-10-24 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0009_update_alert_level_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studio_django_yolo.modelcategory",
                verbose_name="关联类别",
            ),
        ),
    ]
