# Generated by Django 5.2.6 on 2025-10-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0010_add_category_to_alert"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alert",
            table="studio_django_yolo_alert",
        ),
        migrations.AlterModelTable(
            name="detectionrecord",
            table="studio_django_yolo_detection_record",
        ),
        migrations.AlterModelTable(
            name="modelcategory",
            table="studio_django_yolo_model_category",
        ),
        migrations.AlterModelTable(
            name="yolomodel",
            table="studio_django_yolo_yolo_model",
        ),
    ]
