# Generated by Django 5.1.2 on 2025-11-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo", "0012_add_dataset_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_level",
            field=models.CharField(
                choices=[
                    ("high", "高"),
                    ("medium", "中"),
                    ("low", "低"),
                    ("none", "无"),
                ],
                default="medium",
                max_length=10,
                verbose_name="告警等级",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("is_confirm", "已处理"),
                    ("false_positive", "误报"),
                ],
                default="pending",
                max_length=30,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="modelcategory",
            name="alert_level",
            field=models.CharField(
                choices=[
                    ("high", "高"),
                    ("medium", "中"),
                    ("low", "低"),
                    ("none", "无"),
                ],
                default="medium",
                max_length=30,
                verbose_name="告警等级",
            ),
        ),
    ]
