# Generated by Django 5.1.2 on 2025-11-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "studio_django_yolo",
            "0013_alter_alert_alert_level_alter_alert_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_family",
                    models.CharField(max_length=20, verbose_name="YOLO版本"),
                ),
                (
                    "model_size",
                    models.CharField(blank=True, max_length=5, verbose_name="模型大小"),
                ),
                (
                    "weight_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="预训练权重路径"
                    ),
                ),
                (
                    "config_path",
                    models.CharField(max_length=500, verbose_name="模型配置路径"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "训练中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("canceled", "已取消"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "logs_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="日志文件路径"
                    ),
                ),
                (
                    "runs_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="训练输出目录"
                    ),
                ),
                (
                    "best_model_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="best.pt路径"
                    ),
                ),
                (
                    "last_model_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="last.pt路径"
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                ("epochs", models.IntegerField(default=100, verbose_name="轮次")),
                ("imgsz", models.IntegerField(default=640, verbose_name="图像尺寸")),
                ("batch", models.IntegerField(default=16, verbose_name="批大小")),
                (
                    "device",
                    models.CharField(default="0", max_length=50, verbose_name="设备"),
                ),
                (
                    "optimizer",
                    models.CharField(
                        default="SGD", max_length=50, verbose_name="优化器"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="studio_django_yolo.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练任务",
                "verbose_name_plural": "训练任务",
                "db_table": "studio_django_yolo_train_job",
                "ordering": ["-created_at"],
            },
        ),
    ]
