# Generated by Django 5.1.2 on 2025-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo_train", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "排队中"),
                    ("running", "训练中"),
                    ("canceling", "取消中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("canceled", "已取消"),
                ],
                default="queued",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
