# Generated by Django 5.1.2 on 2025-11-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio_django_yolo_train", "0002_alter_trainingjob_status"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="trainingjob",
            table="hertz_yolo_train_train_job",
        ),
    ]
