# Generated by Django 5.1.2 on 2025-11-26 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KBEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hertz_kb_entity",
                "indexes": [
                    models.Index(fields=["name"], name="hertz_kb_en_name_5ce098_idx"),
                    models.Index(fields=["type"], name="hertz_kb_en_type_bbfd75_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KBItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("code", "code"),
                            ("image", "image"),
                            ("audio", "audio"),
                            ("video", "video"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("text", "text"), ("file", "file"), ("url", "url")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="kb/")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hertz_kb_item",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KBChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(default=0)),
                ("text", models.TextField()),
                ("embedding", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="studio_django_kb.kbitem",
                    ),
                ),
            ],
            options={
                "db_table": "hertz_kb_chunk",
                "ordering": ["item_id", "index"],
            },
        ),
        migrations.CreateModel(
            name="KBRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="studio_django_kb.kbentity",
                    ),
                ),
                (
                    "source_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio_django_kb.kbchunk",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="studio_django_kb.kbentity",
                    ),
                ),
            ],
            options={
                "db_table": "hertz_kb_relation",
                "indexes": [
                    models.Index(
                        fields=["relation_type"], name="hertz_kb_re_relatio_7391e7_idx"
                    )
                ],
            },
        ),
    ]
